### ISSUE TITLE
problema en conexion.php

### ISSUE THREAD

**Issue by JonathanFerrucho** [Nicolaysito/Hobbyonthego#11]
hay redundancia de estas lineas:
$dataDB = new dataDB;	

$connection= new mysqli($dataDB->getHost(), $dataDB->getUsername(), $dataDB->getPass(), 

$dataDB->getDB()) or die ("Error al Conecatar con la base de datos");

$rs= $connection->query($query);

**Comment by nicolay-dev** [comment]
Solucionado con commit 5e36925
