### ISSUE TITLE
Desacoplar y organizar en métodos la operación de conectarse a la base de datos

### ISSUE THREAD

**Issue by nicolay-dev** [Nicolaysito/Hobbyonthego#2]
En el archivo **cargar.php** y **guardar.php** el código se puede mejorar y desacoplar para implementar pruebas unitarias

**Comment by JonathanFerrucho** [comment]
Se dejo de utilizar el archivo caragar.php ya que fue relazado por los archivos corespondiantes a un genero tratado e el issue#5.
al  archivo guardar.php se optimizo por funciones
