### ISSUE TITLE
Nueva Funcionalidad de organizar por género

### ISSUE THREAD

**Issue by nicolay-dev** [Nicolaysito/Hobbyonthego#5]
El sistema debe ser capas de mostrar y filtrar al usuario la lista de actividades por genero

**Comment by nicolay-dev** [comment]
Géneros sugeridos:

- Actividad Física

- Viajes

- Películas

- Aire Libre

- Fiesta

- Comida

**Comment by JonathanFerrucho** [comment]
para la aplicación se decido agregar a la nueva funcíon de generos: Actividad Física, Películas , Aire libre y Fiesta.
estos generos se lograron crear con satisfacción
